# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
dizi = np.array([42, 17, 89, 3, 25])
print("Orijinal Dizi:", dizi)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sirali_dizi = np.sort(dizi)
print("Sıralanmış Dizi:", sirali_dizi)

Orijinal Dizi: [42 17 89  3 25]
Sıralanmış Dizi: [ 3 17 25 42 89]


# Problem 2

In [3]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
dizi1 = np.array([10, 15, 30, 45, 60])
print("1. Dizi:", dizi1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
dizi2 = np.arange(5, 16)
print("2. Dizi:", dizi2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
dizi3 = np.arange(50, 101, 5)
print("3. Dizi:", dizi3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
dizi4 = np.zeros(10)
print("4. Dizi:", dizi4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
dizi5 = np.ones(10)
print("5. Dizi:", dizi5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
dizi6 = np.linspace(0, 100, 5)
print("6. Dizi:", dizi6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
dizi7 = np.random.randint(10, 30, 5)
print("7. Dizi:", dizi7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
dizi8 = np.random.uniform(-1, 1, 10)
print("8. Dizi:", dizi8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris = np.random.randint(10, 50, (3, 5))
print("9. Matris:\n", matris)


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplam = np.sum(matris, axis=1)
sutun_toplam = np.sum(matris, axis=0)
print("10. Satır Toplamları:", satir_toplam)
print("10. Sütun Toplamları:", sutun_toplam)


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print("11. En büyük:", matris.max())
print("11. En küçük:", matris.min())
print("11. Ortalama:", matris.mean())


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
indeks = np.argmax(matris)
print("12. En büyük değerin indeksi:", indeks)


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi13 = np.arange(10, 21)
print("13. İlk 3 Eleman:", dizi13[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print("14. Ters Dizi:", dizi13[::-1])


# 15- Üretilen matrisin ilk satırını seçiniz.
print("15. İlk Satır:", matris[0])


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("16. 2. Satır 3. Sütun:", matris[1, 2])


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("17. Her satırın ilk elemanı:", matris[:, 0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print("18. Kareler:\n", np.square(matris))

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris19 = np.random.randint(-50, 51, (3, 5))
print("19. Yeni Matris:\n", matris19)
pozitif_ciftler = matris19[(matris19 > 0) & (matris19 % 2 == 0)]
print("19. Pozitif Çift Sayılar:", pozitif_ciftler)

1. Dizi: [10 15 30 45 60]
2. Dizi: [ 5  6  7  8  9 10 11 12 13 14 15]
3. Dizi: [ 50  55  60  65  70  75  80  85  90  95 100]
4. Dizi: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5. Dizi: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
6. Dizi: [  0.  25.  50.  75. 100.]
7. Dizi: [23 17 11 26 10]
8. Dizi: [-0.77355996  0.89528871 -0.90029     0.1923529  -0.29429354  0.35025798
  0.44260687 -0.88769356  0.88864148  0.37980888]
9. Matris:
 [[49 18 48 34 33]
 [25 48 43 39 10]
 [15 42 29 13 32]]
10. Satır Toplamları: [182 165 131]
10. Sütun Toplamları: [ 89 108 120  86  75]
11. En büyük: 49
11. En küçük: 10
11. Ortalama: 31.866666666666667
12. En büyük değerin indeksi: 0
13. İlk 3 Eleman: [10 11 12]
14. Ters Dizi: [20 19 18 17 16 15 14 13 12 11 10]
15. İlk Satır: [49 18 48 34 33]
16. 2. Satır 3. Sütun: 43
17. Her satırın ilk elemanı: [49 25 15]
18. Kareler:
 [[2401  324 2304 1156 1089]
 [ 625 2304 1849 1521  100]
 [ 225 1764  841  169 1024]]
19. Yeni Matris:
 [[-42 -40  22 -47  32]
 [ 37   7 -36  11 -18]
 [ 16 -27   9