# Problem 1

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0, 10, 5)
print("Matris:", matris)

# 3 - matris'in boyutunu öğrenin
print("Matrisin boyutu:", matris.shape)

# 4 - matris'i yeniden boyutlandırın
matris = matris.reshape(1, 5)
print("Yeniden boyutlandırılmış matris:", matris)

# 5 - matris'in boyut sayısını öğrenin
print("Matrisin boyut sayısı:", matris.ndim)

Matris: [4 4 5 2 5]
Matrisin boyutu: (5,)
Yeniden boyutlandırılmış matris: [[4 4 5 2 5]]
Matrisin boyut sayısı: 2


# Problem 2

In [4]:
import numpy as np

# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
tek_sayilar = np.arange(1, 10, 2)  # [1, 3, 5, 7, 9]
matris = np.reshape(tek_sayilar, (1, 5))
print("Orijinal Matris:\n", matris)

# 2 - Oluşturduğunuz matrisi parçalayın
parca1, parca2 = np.array_split(matris, 2, axis=1)
print("Parça 1:\n", parca1)
print("Parça 2:\n", parca2)

# 3 - Parçalanmış matrisleri birleştirin
birlesmis_matris = np.hstack((parca1, parca2))
print("Birleşmiş Matris:\n", birlesmis_matris)


Orijinal Matris:
 [[1 3 5 7 9]]
Parça 1:
 [[1 3 5]]
Parça 2:
 [[7 9]]
Birleşmiş Matris:
 [[1 3 5 7 9]]


# Problem 3

In [5]:
import numpy as np

# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
sayilar = np.arange(5, 101, 2)  # [5, 7, 9, ..., 99] arası 2'şer artan sayılar
matris = np.random.choice(sayilar, size=10, replace=False)  # tekrar etmeyen 10 rastgele sayı
matris = matris.reshape(2, 5)  # 2x5'lik matris yap
print("Matris:\n", matris)

# 2 - matris'in özelliklerini inceleyin
print("\nMatris Özellikleri:")
print("Boyut (shape):", matris.shape)
print("Boyut Sayısı (ndim):", matris.ndim)
print("Eleman Sayısı (size):", matris.size)
print("Veri Tipi (dtype):", matris.dtype)
print("Minimum Değer:", matris.min())
print("Maksimum Değer:", matris.max())
print("Ortalama:", matris.mean())
print("Standart Sapma:", matris.std())


Matris:
 [[63 37 21 35 59]
 [79 91 33 23 81]]

Matris Özellikleri:
Boyut (shape): (2, 5)
Boyut Sayısı (ndim): 2
Eleman Sayısı (size): 10
Veri Tipi (dtype): int64
Minimum Değer: 21
Maksimum Değer: 91
Ortalama: 52.2
Standart Sapma: 24.36719105682885
